# Generated by Django 4.2.7 on 2023-12-14 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_postmovie_postphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmovie",
            name="postphoto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="post.postphoto",
            ),
            preserve_default=False,
        ),
    ]
